### ISSUE TITLE
ID2: Make PKCE required  in the spec

### ISSUE THREAD

**Issue by bruno-ortizgb** [OpenBanking-Brasil/specs-seguranca#141] opened 2021-06-25 15:22 UTC
I understand that the FAPI specification makes the use of PKCE mandatory when PAR is used. 
But i think that it would be beneficial for the ecosystem if PKCE was required for all cases.

For reference: https://datatracker.ietf.org/doc/html/rfc7636

**Comment by ginglass** [comment] 2021-06-25 15:49
Hello Bruno. 

I agree with you. I don´t know why FAPI WG explicity removes this requirement that is present on FAPI Basic (Part 1) profile item 7... but I supose there is a big issue I don´t know yet :-)

As part of FAPI Part 2 Advanced you´ll find: 

"The authorization server shall support the provisions specified in clause 5.2.2 of Financial-grade API Security Profile 1.0 - Part 1: Baseline, with the **exception that Section 5.2.2-7 (enforcement of RFC7636) is not required**.

It could be a pont to be discussed on a new version of this specs.

**Comment by bruno-ortizgb** [comment] 2021-06-25 16:45
Hi @ginglass thanks for the quick reply! I think that this exception in fapi advanced was made because of the prohibition of "public" clients, so if a client is "confidential" my understanding is that the token exchange is protected by other means, like mTLS, private_key_jwt, etc, nevertheless i think that this could bring a bit more of "security" to the ecosystem given that people still have concerns about the confiability of the hybrid flow.

**Comment by RalphBragg** [comment] 2021-06-27 14:45
The reason that PKCE was not mandated was that hybrid flow, if well implemented by clients, offers the same protection. The key point is that PKCE pulls this protection to the server side (OP) so it is arguably more secure from an ecosystem point of view because OP's have tended to be the only participant that was tested. 

It also wasn't mandated for FAPI 1 for backwards compatibility reasons for hybrid flow.

In reality, most ecosystems haven't required RP's to be tested, this means that Hybrid Flow protections aren't being confirmed as being correctly done by Relying Parties. e.g in the UK, there are real demonstrations of code mix up attacks being performed in the wild and this is only possible because RPs aren't certified. In Brazil RPs *apparently* are going to be certified which should mean that Hybrid Flow is enough.

Given that there are a lot of Banks that are going to implement PAR and PAR is required to support PKCE. All TPPs will be required to support PKCE so there's no issue from a TPP point of view adding this clause to the security profile.

From a Banks point of view, mandating PKCE is a good idea as it ensures that TPPs havent' been subjected to a TPP code attack that they've failed to recognise.

PKCE should be MANDATORY if the ecosystem isn't going to certify RPs.
If the ecosystem isn't going to mandate PKCE AND it is certifying Relying Parties are diong the right thing then technically Hybrid Flow offers the same protection.

**Comment by RalphBragg** [comment] 2021-07-12 08:08
@ginglass  - can you propose a PR for ID2 please for the Banks to require PKCE for redirect (Authorizaiton Server Provisions) and the Client Provisions to shall use PKCE for redirect.

**Comment by OpenBankingBrasil-git** [comment] 2021-07-15 15:38
Has the Security WG Agreed on updating the specs to include the PKCE? 

If not are you planning to take this to the Securtiy WG? This might impact the RP Certification Policy as having the PKCE decreases the risk of having non-certified RP.

@ginglass @joaorodolfo

**Comment by EkkeErick** [comment] 2021-07-15 15:42
Has the Security WG Agreed on updating the specs to include the PKCE?

If not are you planning to take this to the Securtiy WG? This might impact the RP Certification Policy as having the PKCE decreases the risk of having non-certified RP.

@ginglass @joaorodolfo

**Comment by joaorodolfo** [comment] 2021-07-15 21:31
Tks @EkkeErick, it's should be presented into Security WG. 

I’m just thinking it's should be presented after close the gaps from Fase 2/go live subjects I also have a question, Who will introduce it using a compressive benchmarking wich a list of pros and cons for the Sec WG?

**Comment by ginglass** [comment] 2021-07-16 14:48
Hi folks.

Finaly we discuss this point at security WG and, despite of the relevance of RP certification,  we decide that PKCE should not be mandatory by now. OBB sec profile (and FAPI-1-Advanced) requires confidential clients and MTLS (with confidence granted by ICP-Brasil) to token exchange, so PKCE doesn't help to avoid relevant threats. 

Can I close this ticket?

Best regards,

**Comment by joaorodolfo** [comment] 2021-07-19 00:44
Yes.

**Closed** 2021-08-02 13:34 UTC
Labels: enhancement
