### ISSUE TITLE
ID1 - Unintended Normative Change, Is UserInfo Endpoint Required?

### ISSUE THREAD

**Issue by alexasensio** [OpenBanking-Brasil/specs-seguranca#96] opened 2021-06-11 09:38 UTC
FAPI Brasil refers to OIDC, which includes userinfo in their spec, however the documentation in [Github](https://openbanking-brasil.github.io/areadesenvolvedor/#introducao) does not refer anymore to userinfo (changed on 2021.06.09).

Do we need to build a userinfo endpoint?

**Comment by RalphBragg** [comment] 2021-06-11 10:51
Thanks @alexasensio, this removal of the requirement to support userinfo from the documentation page without there being a corresponding explicit requirement in the specification would count as an accidental normative change.

Personally i believe a user info endpoint should still be required but it is up to the security WG.

@alex-siqueira @DeiGratia33  - need an answer on this sharpish as this is an unitended specifation change by removing the requirement for userinfo from the public document.

Option 1: Drop user info support (participants would have to rely on id_tokens ) and so would be refreshing the token to get new ones.
Option 2: Formally add the requirement to support userinfo into the security profile and say it was a non normative change because the requirement was listed on Open Banking Brasil Security Guidelines.
Option 3: Formally add the requirement to support userinfo and publish an ID2. (New Version).

**Comment by ginglass** [comment] 2021-06-14 20:01
In fact, there was a mention about id tokens and userinfo endpoint but I think it was just a reference do OIDC Core... I thought it (offer a userinfo endpoint) was mandatory to OIDC compliance, but if it is not, my suggestion is to follow the second option proposed by you. I can change the Portuguese version to include some like this:

Authorization server
 14 - shall offer an userinfo endpoint, as defined on OIDC  Core, to provide information related to authenticated user and process.

**Comment by RalphBragg** [comment] 2021-06-14 22:17
We really need the working group to confirm that including this would be a non normative change and if so we can add it and put a test into the test harness to check for support.

**Comment by DeiGratia33** [comment] 2021-06-15 19:38
I agree that this was something that was already included. IMHO: the removal will be more harmfull than add the support.

**Comment by ginglass** [comment] 2021-06-22 17:03
This clause is already present at our security profile...

8. shall implement the user info endpoint as defined in clause 5.3 [OpenID Connect Core][OIDC]

I think it is not a bug. May I close this ticket?

**Comment by RalphBragg** [comment] 2021-06-22 17:16
@ginglass  - you are absolutely correct. I didn't notice that it is still included because it has the wrong name. userinfo is what it should be not 'user info'.

**Closed by RalphBragg** 2021-06-22 17:16 UTC
Labels: bug
