### ISSUE TITLE
Docs for well-known resource config

### ISSUE THREAD

**Issue by samlarsen1** [OpenBanking-Brasil/specs-seguranca#110] opened 2021-06-15 17:29 UTC
The current docs for the well-known resource config are unclear:
https://openbanking-brasil.github.io/specs-seguranca/aspsp-user-guide.html#13-registering-resources

Do we create a well-known endpoint for each set of versioned APIs?  Are there any real examples of these files you can point us to?

Or are these the same well-known files that define our authorization server config?

**Comment by RalphBragg** [comment] 2021-06-16 04:22
The well-knowns are not required for each versioned APIs. Several Banks have configured their authorization server metadata and their functional API endpoints on the directory already. I'll find a good reference and include it here.

**Comment by michellebandarraChicago** [comment] 2021-12-01 18:40
Hi guys, is this issue still valid or should we close it?

**Comment by joaorodolfo** [comment] 2022-02-17 04:53
@RalphBragg did you have some reference to include here? if not, we can close this ticket. Thanks.

**Comment by pedro-octavio-andrade** [comment] 2022-03-03 13:12
@samlarsen1 @RalphBragg  is this issue still valid? The issue is already solved by the documentations?

**Comment by michellebandarraChicago** [comment] 2022-05-04 20:50
Tema enviado para tratativa pelo GT Especificações

**Closed by michellebandarraChicago** 2022-05-04 20:50 UTC
Labels: question, answered
